### ISSUE TITLE
[Bug] Data type conflict

### ISSUE THREAD

**Issue by maxmosk** [mregorova/Stack#7]
https://github.com/mregorova/Stack/blob/414045f5ceb1f2c242550c00046b203ed42788bb/stack_new_era.cpp#L64
Why you use float? You should use your typedef for more code flexability

**Comment by nerett** [comment]
# Написал ишью? Чел хорош!
![скелетон](https://user-images.githubusercontent.com/89396128/165822154-442574c9-50bb-4556-9ec8-7df57a7ea859.png)
# А слабо пофиксить баг со `stat` в гну-корявове?

**Comment by maxmosk** [comment]
> # Написал ишью? Чел хорош!
> 
> ![скелетон](https://user-images.githubusercontent.com/89396128/165822154-442574c9-50bb-4556-9ec8-7df57a7ea859.png)
> # А слабо пофиксить баг со `stat` в гну-корявове?

Мегахорош я считаю)
